    // Unexpire passwords to simplify dev mode. Comment these two lines for Production use
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    // comment the line below for production images
    zpm "install passwordless"


    // load all the code of the project as a ZPM package
    zn "USER"

    zpm "load /home/irisowner/dev/ -v":1

    ;Load a test production
    do $System.OBJ.LoadDir("/home/irisowner/dev/src/Test","ck",,1)

    halt
